name: PR Checker

env:
  SRC_WORKING_DIR: "src"
  TEST_WORKING_DIR: "test"
  
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
          
      - name: Restore dependencies
        working-directory: ${{ env.SRC_WORKING_DIR }}
        run: dotnet restore
        
      - name: Build
        working-directory: ${{ env.SRC_WORKING_DIR }}
        run: dotnet build --no-restore
        
      - name: Test
        working-directory: ${{ env.TEST_WORKING_DIR }}
        run: dotnet test --no-build --verbosity normal

    