name: Publish Authentication JWT

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/Api.Security.Authentication.Jwt/**"
  workflow_dispatch:

jobs:
  publish-nuget:
    permissions:
      packages: write
    uses: ./.github/workflows/publish-nuget.yml
    with:
      project_working_dir: "src/Api.Security.Authentication.Jwt"
      dotnet_version: '9.0.x'
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
