name: Publish Authentication

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/Api.Authentication/**"
  workflow_dispatch:

jobs:
  publish-nuget:
    permissions: 
      packages: write
    uses: ./.github/workflows/publish-nuget.yml
    with:
      project_working_dir: "src/Api.Authentication"
      dotnet_version: '9.0.x'
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
